/**
 * Loads the translations generated by `pnpm gt translate` (see gt.config.json,
 * `files.gt.output`). Bundled locally so production needs no runtime API.
 */
export default async function loadTranslations(
  locale: string,
): Promise<Record<string, unknown>> {
  try {
    const translations = await import(`../public/_gt/${locale}.json`);
    return translations.default;
  } catch {
    return {};
  }
}
